sudo: required
services:
  - docker

before_install:
  - docker build -t ylhoony/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ylhoony/react-test npm test -- --coverage

after_success: 
  - docker build -t ylhoony/multi-client ./client
  - docker build -t ylhoony/multi-nginx ./nginx
  - docker build -t ylhoony/multi-server ./server
  - docker build -t ylhoony/multi-worker ./worker

